.releaserc
This PR makes sure the generated CHANGELOG.md is comitted after release.
=> ci(semantic release): commit CHANGELOG.md on release

src/utils/serveComponentSet.ts
=> fix: add cache-control header to dev server

src/bb-components-publish.ts
No longer publish partials since they are removed from the component
sets
=> fix: remove partials from publish command

src/bb-components-generate.ts, src/bb-components.ts, src/types.ts
Added a command to generate boilerplate components `bb components
generate <name>`
fixes #69
=> feat: generate boilerplate components

assets/component-set/__package.json, src/bb-bundle-init.ts, src/bb-bundle.ts, src/bb-components-build.ts, src/bb-components-create.ts, src/bb-components-generate.ts, src/bb-components-publish.ts, src/bb-components-serve.ts, src/bb.ts, src/utils/serveComponentSet.ts, src/utils/servePreview.ts, src/utils/uploadBlob.ts, src/utils/validation.ts, src/validations/component.ts, src/validations/prefab.ts
Improved error handling while running yarn dev in a component set.
Improved visibility for all errors
=> feat: improve error feedback

src/bb-components-build.ts
Raise an exception if a component or prefab does not return anything
=> Fix/error handling build step (#90)

src/bb-components-add.ts, src/bb-components-build.ts, src/bb-components-create.ts, src/bb-components-generate.ts, src/bb-components-init.ts, src/bb-components-install.ts, src/bb-components-publish.ts, src/bb-components-remove.ts, src/bb-components-serve.ts, src/utils/getRootDir.ts, src/utils/serveComponentSet.ts, src/utils/servePreview.ts, src/utils/validation.ts
Fixed that certain commands cannot be used outside of the project folder
anymore by checking for the root dir.
=> fix: refactored error catching and verify rootdir for specific commands

src/validations/constants.ts
introduce a new option type AUTHENTICATION_PROFILE.
This option will be used to select an authentication profile for the MeContainer component.
=> feat: allow option type AUTHENTICATION_PROFILE

src/validations/constants.ts
Allow the new Action Properties option to be used in component sets
=> feat: allow actionProperties as an option

__tests__/validations/actions.test.tsx, __tests__/validations/variable.test.tsx, src/types.ts, src/validations/constants.ts, src/validations/prefab.ts, src/validations/prefab/action.ts, src/validations/prefab/variable.ts
You can now configure update and create action events from the action entity
=> fix: configurable event options art 2744

src/validations/constants.ts
- icons for update form and create form
=> fix: support new component prefab icons

src/validations/constants.ts
- Builders can now use the LoginFormIcon inside there prefab
=> feat: login form icon

__tests__/validations/actions.test.tsx, src/validations/prefab/action.ts
- Builders can now create an delete event with a configured object
=> feat: support delete action event

__tests__/interaction-compatibility.test.ts, src/interactions/compatibility.ts, src/types.ts
- return type of Void is now accepted
=> feat: global void type interactions are now valid

__tests__/validations/variable.test.tsx, src/validations/constants.ts, src/validations/prefab/variable.ts
- add Integer to VARIABLE_KINDS
- add pageId to variable schema
=> fix: add Integer to allowed variable_kinds and allow pageId for variable

src/bb-functions-publish.ts, src/utils/ide.ts
Defaults to <identifier>.bettyblocks.com
=> feat: add host option to bb functions publish

package.json, src/utils/ide.ts, yarn.lock
Both logging in via both Cassie and FusionAuth is supported
=> feat: support logging in with FusionAuth

assets/app-functions/templates/say-hello.js
This update just makes sure that new functions projects are initialised correctly.
=> feat: update sayHello template to reflect latest ActionsJS

src/utils/fusionAuth.ts, src/utils/ide.ts, src/utils/publishAppFunctions.ts, src/utils/publishCustomFunctions.ts
This PR adds the possibility to discern between the multiple zones we have.
Especially between Edge, Acceptance and Production zones.
=> feat: add Zone detection to functions publish

src/utils/login.ts
Except for the 242 that says 2FA is required.
=> feat: allow any 200-ish to be seen as successful login

src/bb-functions-login.ts, src/functions/publishAppFunctions.ts, src/utils/login.ts
This is so that we can guarantee the application that we login with.
=> feat: add applicationId to `api/login`

src/functions/config.ts
=> fix: update fusion auth url

README.md, package.json, src/functions/testRunner.ts, yarn.lock
add isolated-vm as optional dependency
=> feat: add isolated-vm as optional dependency

package-lock.json, package.json, src/bb-components-build.ts
The compiler will filter out all files that do not have 'prefab' in the pathname. It's better to add it, then to change the filter-criteria
=> fix: add prefab to the path of the temp prefab file

__tests__/validations/component.test.tsx, src/validations/prefab/componentOption.ts
changed the naming from showThemeColor to 'showTextStyleColor'
=> fix: rename show theme color

src/bb-components-publish-bundle.ts, src/bb-components-publish.ts, src/functions/bb-components-functions.ts, src/utils/uploadBlob.ts
I have created a new function that can be manually triggered in the github pipelines to release a new bundle.js to the buckets.
=> feat: create publish bundle function
